export const INITIALIZE_ON_SUCCESS = 'INITIALIZE_ON_SUCCESS';

export const AUTH_FETCHING_ON_TOGGLE = 'AUTH_FETCHING_ON_TOGGLE';
export const AUTH_ON_SUCCESS = 'AUTH_ON_SUCCESS';
export const DE_AUTH = 'DE_AUTH';

export const CREATE_POST_FETCHING_ON_PROGRESS = 'CREATE_POST_FETCHING_ON_PROGRESS';
export const CREATE_POST_FETCHING_ON_ERROR = 'CREATE_POST_FETCHING_ON_ERROR';
export const CREATE_POST_FETCHING_ON_SUCCESS = 'CREATE_POST_FETCHING_ON_SUCCESS';
export const CREATE_POST_FORM_IS_OPEN = 'CREATE_POST_FORM_IS_OPEN';

export const POSTS_FETCHING_ON_PROGRESS = 'POSTS_FETCHING_ON_PROGRESS';
export const POSTS_FETCHING_ON_SUCCESS = 'POSTS_FETCHING_ON_SUCCESS';
export const POSTS_FETCHING_ON_ERROR = 'POSTS_FETCHING_ON_ERROR';
export const ADD_POST = 'ADD_POST';
export const PUT_LIKE_ON_POST = 'PUT_LIKE_ON_POST';
export const LIKE_FETCHING_TOGGLE = 'LIKE_FETCHING_TOGGLE';

export const PROFILE_INIT_TOGGLE = 'PROFILE_INIT_TOGGLE';
export const POST_DELETING_TOGGLE = 'POST_DELETING_TOGGLE';
export const POST_DELETING_ON_ERROR = 'POST_DELETING_ON_ERROR';
export const POST_DELETING_ON_SUCCESS = 'POST_DELETING_ON_SUCCESS';
export const SET_USER_DATA = 'SET_USER_DATA';
export const VIEW_MODE_TOGGLE = 'VIEW_MODE_TOGGLE';
export const DELETE_USER_DATA = 'DELETE_USER_DATA';
export const CHANGE_REMOVE_REQUEST_TOGGLE = 'CHANGE_REMOVE_REQUEST_TOGGLE';
export const CHANGE_REMOVE_REQUEST_ON_SUCCESS = 'CHANGE_REMOVE_REQUEST_ON_SUCCESS';

export const USERS_FETCHING_ON_PROGRESS = 'USERS_FETCHING_ON_PROGRESS';
export const USERS_FETCHING_ON_SUCCESS = 'USERS_FETCHING_ON_SUCCESS';
export const USERS_FETCHING_ON_ERROR = 'USERS_FETCHING_ON_ERROR';
export const DELETE_USER_FETCHING_ON_PROGRESS = 'DELETE_USER_FETCHING_ON_PROGRESS';
export const DELETE_USER_FETCHING_ON_SUCCESS = 'DELETE_USER_FETCHING_ON_SUCCESS';
export const DELETE_USER_FETCHING_ON_ERROR = 'DELETE_USER_FETCHING_ON_ERROR';
